### ISSUE TITLE
Nice! Feedback...

### ISSUE THREAD

**Issue by idkjs** [drejohnson/reason-react-fullstack-graphql#1]
Some quick feed back. Instruction on readme are not clear to me.  Thoughts:
1. To run the server, might mention that you have to have docker installed for the uninitiated, for prisma to run local. 
2. Before running the server, you have to build it with `yarn build` or `yarn watch`. I did this by adding following scripts:
```
  "scripts": {
 ...
    "build": "bsb -make-world -clean-world",
    "watch": "bsb -make-world -clean-world -w"
  },
```
3. Run `yarn start` from src/server and that will get the server going.
4. You have the prisma and playground scripts in server/package.json. What is the purpose of those scripts? Seems like they arent doing anything. At any rate, they throw errors without any additional config.  As result, `yarn dev` doesnt work either. Is it intended that playground doesnt work with this server set up? prisma playground relies on prisma.yml but dont know if you left that out on purpose. Is a user expected to be able to deploy this demo as is?

**Comment by drejohnson** [comment]
Thanks, I've updated the readme. It was using the boilerplate readme from https://github.com/graphql-boilerplates/react-fullstack-graphql/tree/master/minimal. I also removed the prisma scripts since prisma bindings aren't complete.

**Comment by idkjs** [comment]
Cool. Just a heads up. Thanks for sharing.
